
export const playlists = [{
  title: "$5song",
  artist: "tttttt!",
  album: " aaaa",
  track: "$aaaaaaa",
  year: "1",
  img_src: "$orries_Cover (front)_e.jpg",
  src: "5song.mp3",
},{
  title: "$orries",
  artist: "Peachy!",
  album: " Shiloh",
  track: "$orries",
  year: "1",
  img_src: "$orries_Cover (front)_e.jpg",
  src: "$orries.mp3",
},
  {
    title: "[oops]",
    artist: "potsu",
    album: "[oops]",
    track: "1",
    year: "",
    img_src: "[oops]_Cover (front)_e.jpg",
    src: "[oops].mp3",
  },
  {
    title: "5:32pm",
    artist: "The Deli",
    album: "Vibes 2",
    track: "12",
    year: "",
    img_src: "5 32pm_Cover (front)_e.jpg",
    src: "5 32pm.mp3",
  },
  {
    title: "88 Keys",
    artist: "Oatmello",
    album: "Snapshots",
    track: "3",
    year: "",
    img_src: "88 Keys_Cover (front)_e.jpg",
    src: "88 Keys.mp3",
  },
  {
    title: "Affection",
    artist: "Jinsang",
    album: "Life",
    track: "15",
    year: "",
    img_src: "Affection_Cover (front)_e.jpg ",
    src: "Affection.mp3",
  },
  {
    title: "Again",
    artist: "Wun Two",
    album: "Penthouse",
    track: "4",
    year: "",
    img_src: "Again_Cover (front)_e.jpg",
    src: "Again.mp3",
  },
  {
    title: "Alone and Lonely",
    artist: "prxz",
    album: " Shiloh Dynasty",
    track: "Love Wounds",
    year: "2",
    img_src: "Alone and Lonely_Cover (front)_e.jpg",
    src: "Alone and Lonely.mp3",
  },
  {
    title: "Baby You're Worth It",
    artist: "Kina",
    album: "Baby You're Worth It",
    track: "1",
    year: "",
    img_src: "Baby You're Worth It_Cover (front)_e.jpg",
    src: "Baby You're Worth It.mp3",
  },
  {
    title: "Backpack City",
    artist: "Flovry",
    album: " tender spring",
    track: "Ages Ago",
    year: "4",
    img_src: "Baby You're Worth It_Cover (front)_e.jpg",
    src: "Backpack City.mp3",
  },
  {
    title: "Beauty",
    artist: "eyeroze",
    album: "Heartless",
    track: "4",
    year: "",
    img_src: "Beauty_Cover (front)_e.jpg",
    src: "Beauty.mp3",
  },
  {
    title: "Better Than He Can",
    artist: "Jennifer Flores",
    album: " Shiloh Dynasty",
    track: " LofiCentral",
    year: "All My Love",
    img_src: "Better Than He Can_Cover (front)_e.jpg",
    src: "Better Than He Can.mp3",
  },
  {
    title: "Break My Heart Again",
    artist: "90degrees",
    album: "Break My Heart Again",
    track: "1",
    year: "",
    img_src: "Break My Heart Again_Cover (front)_e.jpg",
    src: "Break My Heart Again.mp3",
  },
  {
    title: "Brightness",
    artist: "eyeroze",
    album: "Heartless",
    track: "15",
    year: "",
    img_src: "Brightness_Cover (front)_e.jpg",
    src: "Brightness.mp3",
  },
  {
    title: "Call me",
    artist: "90sFlav",
    album: "Collection",
    track: "1",
    year: "",
    img_src: "Call me_Cover (front)_e.jpg",
    src: "Call me.mp3",
  },
  {
    title: "Can We Kiss Forever?",
    artist: "Kina",
    album: " Adriana Proenza",
    track: "Can We Kiss Forever?",
    year: "1",
    img_src: "Can We Kiss Forever _Cover (front)_e.jpg",
    src: "Can We Kiss Forever .mp3",
  },
  {
    title: "Can't Love Myself",
    artist: "Monty Datta",
    album: " Mishaal",
    track: "Can't Love Myself",
    year: "1",
    img_src: "Can't Love Myself_Cover (front)_e.jpg",
    src: "Can't Love Myself.mp3",
  },
  {
    title: "Can't Take My Eyes off You",
    artist: "Craymer",
    album: " AIIVAWN",
    track: "Can't Take My Eyes off You",
    year: "1",
    img_src: "Can't Take My Eyes off You_Cover (front)_e.jpg",
    src: "Can't Take My Eyes off You.mp3",
  },
  {
    title: "Cigarettes and Sex",
    artist: "prxz",
    album: " Shiloh Dynasty",
    track: "Love Wounds",
    year: "1",
    img_src: "Cigarettes and Sex_Cover (front)_e.jpg",
    src: "Cigarettes and Sex.mp3",
  },
  {
    title: "Coffee Breath",
    artist: "eyeroze",
    album: "Coffee Breath",
    track: "1",
    year: "",
    img_src: "Coffee Breath_Cover (front)_e.jpg",
    src: "Coffee Breath.mp3",
  },
  {
    title: "controlla",
    artist: "Idealism",
    album: "rainy evening",
    track: "2",
    year: "",
    img_src: "controlla_Cover (front)_e.jpg",
    src: "controlla.mp3",
  },
  {
    title: "Cream",
    artist: "eyeroze",
    album: "Heartless",
    track: "14",
    year: "",
    img_src: "Cream_Cover (front)_e.jpg",
    src: "Cream.mp3",
  },
  {
    title: "Day in Paris",
    artist: "Llusion",
    album: "Day in Paris",
    track: "1",
    year: "",
    img_src: "Day in Paris_Cover (front)_e.jpg",
    src: "Day in Paris.mp3",
  },
  {
    title: "Daydreaming",
    artist: "eyeroze",
    album: "Heartless",
    track: "8",
    year: "",
    img_src: "Daydreaming_Cover (front)_e.jpg",
    src: "Daydreaming.mp3",
  },
  {
    title: "Death Bed",
    artist: "Fets",
    album: " Koosen",
    track: " Formal Chicken",
    year: "Death Bed",
    img_src: "Death Bed_Cover (front)_e.jpg",
    src: "Death Bed.mp3",
  },
  {
    title: "drift...",
    artist: "junyii.",
    album: " Chill Children",
    track: "junyii・float",
    year: "3",
    img_src: "drift..._Cover (front)_e.jpg",
    src: "drift....mp3",
  },
  {
    title: "Evil Morty",
    artist: "Weegie",
    album: " Koosen",
    track: " Poky",
    year: "Evil Morty",
    img_src: "Evil Morty_Cover (front)_e.jpg",
    src: "Evil Morty.mp3",
  },
  {
    title: "Feblu",
    artist: "Flughand",
    album: "EXPEDITion Vol. 7: Moonloops",
    track: "2",
    year: "",
    img_src: "Feblu_Cover (front)_e.jpg",
    src: "Feblu.mp3",
  },
  {
    title: "Fever Dream",
    artist: "Ethan Rebel",
    album: "Fever Dream",
    track: "1",
    year: "",
    img_src: "Fever Dream_Cover (front)_e.jpg",
    src: "Fever Dream.mp3",
  },
  {
    title: "First Heartbreak",
    artist: "Flovry",
    album: " tender spring",
    track: "Ages Ago",
    year: "3",
    img_src: "First Heartbreak_Cover (front)_e.jpg",
    src: "First Heartbreak.mp3",
  },
  {
    title: "French Inhale",
    artist: "[bsd.u]",
    album: "444",
    track: "2",
    year: "",
    img_src: "French Inhale_Cover (front)_e.jpg",
    src: "French Inhale.mp3",
  },
  {
    title: "Get You The Moon (feat. Snøw)",
    artist: "Kina",
    album: " Snøw",
    track: "Get You The Moon (feat. Snøw)",
    year: "1",
    img_src:
      "Get You The Moon (feat. Snøw)_Cover (front)_e.jpg",
    src: "Get You The Moon (feat. Snøw).mp3",
  },
  {
    title: "Ghost Train Haze",
    artist: "BluntOne",
    album: "Forest Walk",
    track: "1",
    year: "",
    img_src: "Ghost Train Haze_Cover (front)_e.jpg",
    src: "Ghost Train Haze.mp3",
  },
  {
    title: "Happiness",
    artist: "eyeroze",
    album: "Heartless",
    track: "12",
    year: "",
    img_src: "Happiness_Cover (front)_e.jpg",
    src: "Happiness.mp3",
  },
  {
    title: "hold up",
    artist: "eevee",
    album: "beat tape 06",
    track: "2",
    year: "",
    img_src: "hold up_Cover (front)_e.jpg",
    src: "hold up.mp3",
  },
  {
    title: "I Can't Help",
    artist: "Sarcastic Sounds",
    album: "I Can't Help",
    track: "1",
    year: "",
    img_src: "I Can't Help_Cover (front)_e.jpg",
    src: "I Can't Help.mp3",
  },
  {
    title: "I Don't Sleep",
    artist: "Sarcastic Sounds",
    album: "I Don't Sleep",
    track: "1",
    year: "",
    img_src: "I Don't Sleep_Cover (front)_e.jpg",
    src: "I Don't Sleep.mp3",
  },
  {
    title: "I Don't Trust Nobody",
    artist: "cucu",
    album: " Shiloh",
    track: "I Don't Trust Nobody",
    year: "1",
    img_src: "I Don't Trust Nobody_Cover (front)_e.jpg",
    src: "I Don't Trust Nobody.mp3",
  },
  {
    title: "I'll Bite Your Soul",
    artist: "SHRK",
    album: " Shiloh Dynasty",
    track: "Lost in Love",
    year: "3",
    img_src: "I'll Bite Your Soul_Cover (front)_e.jpg",
    src: "I'll Bite Your Soul.mp3",
  },
  {
    title: "I'll Keep You Safe",
    artist: "sagun",
    album: "I'll Keep You Safe",
    track: "1",
    year: "",
    img_src: "I'll Keep You Safe_Cover (front)_e.jpg",
    src: "I'll Keep You Safe.mp3",
  },
  {
    title: "i'm closing my eyes (feat. shiloh)",
    artist: "potsu",
    album: "i'm closing my eyes (feat. shiloh)",
    track: "1",
    year: "",
    img_src:
      "i'm closing my eyes (feat. shiloh)_Cover (front)_e.jpg",
    src: "i'm closing my eyes (feat. shiloh).mp3",
  },
  {
    title: "I'm Drunk and Confused",
    artist: "eyeroze",
    album: " 90degrees",
    track: "I'm Drunk and Confused",
    year: "1",
    img_src: "I'm Drunk and Confused_Cover (front)_e.jpg",
    src: "I'm Drunk and Confused.mp3",
  },
  {
    title: "I'm Shy. I'm Anxious",
    artist: "prxz",
    album: " Shiloh Dynasty",
    track: "Love Wounds",
    year: "3",
    img_src: "I'm Shy. I'm Anxious_Cover (front)_e.jpg",
    src: "I'm Shy. I'm Anxious.mp3",
  },
  {
    title: "I'm Sorry",
    artist: "Swell",
    album: " Shiloh",
    track: "Theres Still Us",
    year: "3",
    img_src: "I'm Sorry_Cover (front)_e.jpg",
    src: "I'm Sorry.mp3",
  },
  {
    title: "I'm Yours",
    artist: "Koosen",
    album: " Avocuddle",
    track: " Fets",
    year: "I'm Yours",
    img_src: "I'm Yours_Cover (front)_e.jpg",
    src: "I'm Yours.mp3",
  },
  {
    title: "In My Eyes",
    artist: "Beowülf",
    album: "In My Eyes",
    track: "1",
    year: "",
    img_src: "In My Eyes_Cover (front)_e.jpg",
    src: "In My Eyes.mp3",
  },
  {
    title: "infinity",
    artist: "Oatmello",
    album: "infinity",
    track: "1",
    year: "",
    img_src: "infinity_Cover (front)_e.jpg",
    src: "infinity.mp3",
  },
  {
    title: "I've Changed for You",
    artist: "Kina",
    album: " Madson Project.",
    track: "I've Changed for You",
    year: "1",
    img_src: "I've Changed for You_Cover (front)_e.jpg",
    src: "I've Changed for You.mp3",
  },
  {
    title: "Kiss",
    artist: "eyeroze",
    album: "Heartless",
    track: "3",
    year: "",
    img_src: "Kiss_Cover (front)_e.jpg",
    src: "Kiss.mp3",
  },
  {
    title: "Landing",
    artist: "dryhope",
    album: "White Oak",
    track: "2",
    year: "",
    img_src: "Landing_Cover (front)_e.jpg",
    src: "Landing.mp3",
  },
  {
    title: "Let Her Go",
    artist: "Sea Flap Flap",
    album: " Weegie",
    track: " Formal Chicken",
    year: "Let Her Go",
    img_src: "Let Her Go_Cover (front)_e.jpg",
    src: "Let Her Go.mp3",
  },
  {
    title: "Long",
    artist: "Shiloh Dynasty",
    album: " LofiCentral",
    track: " Stay Might",
    year: "Remixes",
    img_src: "Long_Cover (front)_e.jpg",
    src: "Long.mp3",
  },
  {
    title: "Loosing Interest",
    artist: "Timmies",
    album: "Passion & Confusion",
    track: "2",
    year: "",
    img_src: "Loosing Interest_Cover (front)_e.jpg",
    src: "Loosing Interest.mp3",
  },
  {
    title: "Losing Interest",
    artist: "itssvd",
    album: " Shiloh Dynasty",
    track: "Missing",
    year: "2",
    img_src: "Losing .Interest_Cover (front)_e.jpg",
    src: "Losing .Interest.mp3",
  },
  {
    title: "Losing Interest",
    artist: "itssvd",
    album: " Shiloh Dynasty",
    track: "Missing",
    year: "2",
    img_src: "Losing Interest(2)_Cover (front)_e.jpg",
    src: "Losing Interest.mp3",
  },
  {
    title: "Losing Interest",
    artist: "Inownlove",
    album: " Shiloh",
    track: "Feel Blue",
    year: "9",
    img_src: "Losing Interest(2)_Cover (front)_e.jpg",
    src: "Losing Interest(2).mp3",
  },
  {
    title: "Love Again",
    artist: "itssvd",
    album: " Shiloh Dynasty",
    track: "Missing",
    year: "1",
    img_src: "Love Again_Cover (front)_e.jpg",
    src: "Love Again.mp3",
  },
  {
    title: "Love Is More Depressing Than Depression",
    artist: "prxz",
    album: " Shiloh Dynasty",
    track: "Love Wounds",
    year: "7",
    img_src:
      "Love Is More Depressing Than Depression_Cover (front)_e.jpg",
    src: "Love Is More Depressing Than Depression.mp3",
  },
  {
    title: "Medieval",
    artist: "eyeroze",
    album: "Heartless",
    track: "9",
    year: "",
    img_src: "Medieval_Cover (front)_e.jpg",
    src: "Medieval.mp3",
  },
  {
    title: "Mirror Image",
    artist: "ENRA",
    album: " Sleepermane",
    track: "Tomorrows That Follow",
    year: "4",
    img_src: "Mirror Image_Cover (front)_e.jpg",
    src: "Mirror Image.mp3",
  },
  {
    title: "Miss You",
    artist: "Monty Datta",
    album: " Shiloh Dynasty",
    track: "Miss You",
    year: "1",
    img_src: "Miss You_Cover (front)_e.jpg",
    src: "Miss You.mp3",
  },
  {
    title: "Monday",
    artist: "eyeroze",
    album: "Heartless",
    track: "2",
    year: "",
    img_src: "Monday_Cover (front)_e.jpg",
    src: "Monday.mp3",
  },
  {
    title: "my new love",
    artist: "Elijah Who",
    album: "Gentle Boy",
    track: "12",
    year: "",
    img_src: "my new love_Cover (front)_e.jpg",
    src: "my new love.mp3",
  },
  {
    title: "nagashi",
    artist: "Idealism",
    album: "rainy evening",
    track: "5",
    year: "",
    img_src: "nagashi_Cover (front)_e.jpg",
    src: "nagashi.mp3",
  },
  {
    title: "Night Walk",
    artist: "xander.",
    album: "Found Memories",
    track: "1",
    year: "",
    img_src: "Night Walk_Cover (front)_e.jpg",
    src: "Night Walk.mp3",
  },
  {
    title: "Nightfall",
    artist: "eyeroze",
    album: "Heartless",
    track: "5",
    year: "",
    img_src: "Nightfall_Cover (front)_e.jpg",
    src: "Nightfall.mp3",
  },
  {
    title: "Nostalgia",
    artist: "eyeroze",
    album: "Heartless",
    track: "7",
    year: "",
    img_src: "Nostalgia_Cover (front)_e.jpg",
    src: "Nostalgia.mp3",
  },
  {
    title: "Not Even Her (feat. Shiloh)",
    artist: "Floreyyyy",
    album: " Shiloh",
    track: "Intimacy",
    year: "8",
    img_src: "Not Even Her (feat. Shiloh)_Cover (front)_e.jpg",
    src: "Not Even Her (feat. Shiloh).mp3",
  },
  {
    title: "Nova",
    artist: "mell-ø",
    album: "1 Am. Study Session",
    track: "6",
    year: "",
    img_src: "Nova_Cover (front)_e.jpg",
    src: "Nova.mp3",
  },
  {
    title: "Oblivion",
    artist: "Rufi-O",
    album: " Lily Potter",
    track: "Oblivion",
    year: "1",
    img_src: "Oblivion_Cover (front)_e.jpg",
    src: "Oblivion.mp3",
  },
  {
    title: "Our Adventures",
    artist: "xander.",
    album: "Found Memories",
    track: "3",
    year: "",
    img_src: "Our Adventures_Cover (front)_e.jpg",
    src: "Our Adventures.mp3",
  },
  {
    title: "over u",
    artist: "keshi",
    album: "over u",
    track: "1",
    year: "",
    img_src: "over u_Cover (front)_e.jpg",
    src: "over u.mp3",
  }
  ];